default: &default
  adapter: postgresql
  username: postgres
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: LuckyFind_development

test:
  <<: *default
  database: LuckyFind_test

production:
  <<: *default
  database: LuckyFind_production
